Repository googleapis/nodejs-error-reporting, pull requests merged in 2019-06, with the labels that each got.

#371 build: remove unused clang format
  .clang-format.yaml
  system-test/error-reporting.ts
Labels: automerge, cla: yes

#372 docs: use repo metadata to generate docs
  .cloud-repo-tools.json
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  config.tar.enc
  js-green-licenses.json
  samples/README.md
  synth.metadata
  synth.py
Labels: cla: yes

#373 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  README.md
  synth.metadata
Labels: cla: yes

#376 fix: bump min required versions and fix package scripts
  package.json
  test/test-servers/koa_scaffold_server.ts
Labels: cla: yes

#375 feat: automatically use service and revision name in Knative environments
  src/configuration.ts
  test/unit/service-configuration.ts
Labels: cla: yes

#378 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#381 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#382 chore: release 1.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#383 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
