Repository googleapis/nodejs-error-reporting, pull requests merged in 2019-05, with the labels that each got.

#348 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#349 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#351 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#354 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#356 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#355 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#350 chore(deps): upgrade to gts 1.0.0
  README.md
  package.json
  src/build-stack-trace.ts
  src/classes/error-message.ts
  src/configuration.ts
  src/google-apis/auth-client.ts
  src/index.ts
  src/interfaces/express.ts
  src/interfaces/hapi.ts
  src/interfaces/koa.ts
  src/interfaces/koa2.ts
  src/interfaces/manual.ts
  src/interfaces/message-builder.ts
  src/interfaces/restify.ts
  src/logger.ts
  src/populate-error-message.ts
  src/request-extractors/express.ts
  src/request-extractors/hapi.ts
  src/request-extractors/koa.ts
  src/request-extractors/manual.ts
  system-test/error-reporting.ts
  system-test/test-install.ts
  test/fixtures/configuration.ts
  test/test-servers/express_scaffold_server.ts
  test/test-servers/hapi_scaffold_server.ts
  test/test-servers/manual_scaffold_server.ts
  test/unit/classes/error-message.ts
  test/unit/configuration.ts
  test/unit/google-apis/auth-client.ts
  test/unit/interfaces/express.ts
  test/unit/interfaces/hapi.ts
  test/unit/interfaces/manual.ts
  test/unit/interfaces/restify.ts
  test/unit/logger.ts
  test/unit/populate-error-message.ts
  test/unit/request-extractors/express.ts
  test/unit/request-extractors/hapi.ts
  test/unit/request-extractors/koa.ts
  test/unit/request-extractors/manual.ts
  test/unit/service-configuration.ts
  test/util.ts
  utils/errors-api-transport.ts
  utils/fuzzer.ts
Labels: :rotating_light:, cla: yes

#353 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, status: blocked

#359 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#360 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#361 refactor: remove request and ineffective tests
  package.json
  system-test/error-reporting.ts
  test/unit/interfaces/manual.ts
Labels: cla: yes

#363 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#365 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#366 chore: update @google-cloud/common to 2.x
  package.json
  src/google-apis/auth-client.ts
Labels: cla: yes

#367 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
