Repository googleapis/nodejs-error-reporting, pull requests merged in 2020-11, with the labels that each got.

#528 test: fix CI failing on new Mocha unhandledRejection listener
  system-test/error-reporting.ts
Labels: api: clouderrorreporting, cla: yes, kokoro:run, priority: p1, type: process

#522 chore: add api-logging to codeowners
  .github/CODEOWNERS
  .readme-partials.yaml
  .repo-metadata.json
  README.md
Labels: api: clouderrorreporting, cla: yes, lang: nodejs, priority: p2, type: cleanup

#529 build: generate up-to-date build config
  .github/workflows/ci.yaml
  .kokoro/release/docs-devsite.sh
  .kokoro/trampoline_v2.sh
  CODE_OF_CONDUCT.md
  synth.metadata
  test/unit/build-stack-trace.ts
Labels: api: clouderrorreporting, cla: yes

#530 chore: add generated files bot config
  .github/generated-files-bot.yml
Labels: api: clouderrorreporting, cla: yes, priority: p2, type: process

#531 docs: update README formatting and branding
  README.md
  samples/README.md
  synth.metadata
Labels: api: clouderrorreporting, cla: yes, context: none

#532 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: api: clouderrorreporting, cla: yes, priority: p2

#533 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full
