Repository googleapis/nodejs-error-reporting, pull requests merged in 2020-04, with the labels that each got.

#461 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes, kokoro:force-run

#462 build: update templates for Node.js libraries
  .eslintrc.json
  .github/workflows/ci.yaml
  .prettierrc.js
  synth.metadata
Labels: cla: yes

#463 fix: apache license URL (#468)
  .prettierrc.js
  synth.metadata
Labels: automerge, cla: yes

#468 build: remove unused codecov config
  codecov.yaml
Labels: automerge, cla: yes

#465 feat!: require node 10 in engines field
  package.json
Labels: automerge, cla: yes

#467 build!: update to latest version of gts and typescript
  .eslintrc.yml
  .prettierignore
  .prettierrc
  package.json
  samples/package.json
  src/google-apis/auth-client.ts
  src/index.ts
  src/interfaces/hapi.ts
  src/logger.ts
  system-test/error-reporting.ts
  system-test/test-install.ts
  test/test-servers/express_scaffold_server.ts
  test/unit/classes/error-message.ts
  test/unit/classes/request-information-container.ts
  test/unit/configuration.ts
  test/unit/google-apis/auth-client.ts
  test/unit/interfaces/hapi.ts
  test/unit/interfaces/restify.ts
  test/unit/logger.ts
  test/unit/populate-error-message.ts
  test/unit/request-extractors/express.ts
  test/unit/request-extractors/hapi.ts
  test/unit/request-extractors/koa.ts
  test/unit/request-extractors/manual.ts
  test/unit/service-configuration.ts
  tsconfig.json
Labels: automerge, cla: yes

#471 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#473 chore: update packages and linting
  package.json
  src/index.ts
  src/interfaces/hapi.ts
  src/interfaces/koa.ts
  src/interfaces/manual.ts
  src/populate-error-message.ts
  system-test/.eslintrc.yml
  system-test/error-reporting.ts
  test/test-servers/hapi_scaffold_server.ts
  test/test-servers/koa_scaffold_server.ts
  test/unit/configuration.ts
  test/unit/interfaces/hapi.ts
  test/unit/interfaces/manual.ts
  test/unit/interfaces/restify.ts
  test/unit/logger.ts
  test/unit/request-extractors/express.ts
  test/util.ts
  tsconfig.json
  utils/errors-api-transport.ts
Labels: cla: yes

#474 build: use codecov's action, now that it's authless
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes

#475 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes
