Repository googleapis/nodejs-error-reporting, pull requests merged in 2021-04, with the labels that each got.

#552 test: patch broken @hapi/podium dependency
  tsconfig.json
Labels: api: clouderrorreporting, cla: yes, priority: p1, type: cleanup

#554 chore: update blunderbuss to auto assign nicole
  .github/blunderbuss.yml
Labels: api: clouderrorreporting, cla: yes

#556 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: api: clouderrorreporting, automerge, cla: yes, context: full

#553 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  owlbot.py
  synth.metadata
  system-test/error-reporting.ts
Labels: api: clouderrorreporting, cla: yes
